
services:
  app:
    build: .
    command: bin/dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
      WEATHER_API_BASE_URL: https://api.weatherapi.com/v1/forecast.json
      WEATHER_API_KEY: cf803cc159ec4d349e9194715253008
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
