---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/forecasts":
    get:
      summary: Retrieves a weather forecast by address
      tags:
      - Forecasts
      parameters:
      - name: address[city]
        in: query
        required: false
        description: City name
        schema:
          type: string
      - name: address[state]
        in: query
        required: false
        description: State code
        schema:
          type: string
      - name: address[zip]
        in: query
        required: false
        description: Zip code
        schema:
          type: string
      - name: address[street]
        in: query
        required: false
        description: Street address
        schema:
          type: string
      - name: days
        in: query
        required: false
        description: Number of days for forecast (1-14)
        minimum: 1
        maximum: 14
        schema:
          type: integer
      - name: unit
        in: query
        required: false
        description: "Unit system (imperial or metric):\n * `imperial` \n * `metric`
          \n "
        enum:
        - imperial
        - metric
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  cached:
                    type: boolean
                  current:
                    type: object
                    properties:
                      condition:
                        type: string
                      uv:
                        type: number
                      temperature:
                        type: number
                      wind:
                        type: object
                        properties:
                          speed:
                            type: number
                          direction:
                            type: object
                            properties:
                              degree:
                                type: integer
                              dir:
                                type: string
                      feels_like:
                        type: number
                  forecast:
                    type: array
                    items:
                      type: object
                      properties:
                        day:
                          type: string
                        max:
                          type: number
                        min:
                          type: number
                        condition:
                          type: string
                        humidity:
                          type: integer
                        chance_of_rain:
                          type: integer
                        chance_of_snow:
                          type: integer
                        hourly:
                          type: array
                          items:
                            type: object
                            properties:
                              time:
                                type: string
                              temperature:
                                type: number
                              condition:
                                type: string
                              feels_like:
                                type: number
                required:
                - cached
                - current
                - forecast
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      street:
                        type: array
                        items:
                          type: string
                      city:
                        type: array
                        items:
                          type: string
                      state:
                        type: array
                        items:
                          type: string
                      zip:
                        type: array
                        items:
                          type: string
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
