name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop
      - name: Run RSpec
        env:
          RAILS_ENV: test
          REDIS_URL: redis://localhost:6379/2
          WEATHER_API_BASE_URL: https://api.weatherapi.com/v1/forecast.json
          WEATHER_API_KEY: cf803cc159ec4d349e9194715253008
        run: bundle exec rspec
